pinme/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    (r'^',include('pinme.main.urls')),
)

pinme/main/models.py
from django.db import models
import datetime

class User(models.Model):
    username = models.CharField(max_length=50)
    email = models.EmailField(default="")
    password_md5 = models.CharField(max_length=32)

    first_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50, null=True)
    about =  models.CharField(max_length=200, null=True)
    site = models.URLField(null=True)

    def __unicode__(self):
        return self.username

class Site(models.Model):
    url=models.URLField(unique=True)

    def __unicode__(self):
        return self.url

class Img(models.Model):
    uploaded_by_user=models.ForeignKey(User)
    src=models.URLField(unique=True)
    site=models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.alt
    
class Category(models.Model):
    name=models.CharField(max_length=100)
    enabled=models.BooleanField(default=True)

    def __unicode__(self):
        return self.name

class Collection(models.Model):
    user=models.ForeignKey(User)
    name=models.CharField(max_length=100)
    category=models.ForeignKey(Category)

    def __unicode__(self):
        return self.name
    
class Pin(models.Model):
    user=models.ForeignKey(User)
    img=models.ForeignKey(Img)
    alt=models.CharField(max_length=100,default='')
    collection=models.IntegerField(default=0)

pinme/templates/collection_edit.html
{% include "header.html" %}
<div id="login_layout">
	<div id="login_sublayout">
		<img src="/static/images/strip.png" alt="strip">
		{% if error_message_list %}
			{% for error_message in error_message_list %}
				<div class="error_message">{{error_message}}</div>
			{% endfor %}
		{% endif %}
		<form method="post" action="" class="login_signin">
			{% csrf_token %}
			<label>Collection Name</label>{{ form.name }}<br />
			{{ form.name.errors }}
			<label>Collection Category</label>{{ form.category }}
			{{ form.category.errors }}
			<br />
			<div class="last_singin">
				<input type="submit" value="Save Collection" class="submit_button">
            </div>
		</form>
	</div>
</div> 

{% include "footer.html" %}

pinme/templates/collection_list.html
{% include "header.html" %}
<div class="wrap_board">
	{% include "profile_my.html" %}
	<div id="collection_bar">
	     <p id="bar_links">
         	<a href="#">Collections</a><span class="bar_links_nb">(1)</span>
			<a href="#">Pins</a><span class="bar_links_nb">(2)</span>		
			<a href="#">Like</a><span class="bar_links_nb">(3)</span>  
		</p>
		 <div style="text-align:right;">
			 <button style="width:200px;" class="button_edit">Select Collection</button></a>
		 </div>
    </div>
    <div id="collection_board">
    	{% for collection in collection_list %}
			<div class="my_collection_board">
				<h3>{{collection.name}}</h3>
				<div class="mini_board">
					<a href="/angelines/favorite-places-spaces/" class="mini_board_link">
	                    <img src="http://media-cdn.pinterest.com/upload/57209857736228243_OUytKj95_t.jpg" alt="Photo of a collection">
	                    <img src="http://media-cdn.pinterest.com/upload/2814818487000488_DGHvJr2p_t.jpg" alt="Photo of a collection">
	                    <img src="http://media-cdn.pinterest.com/upload/18014467229408067_EhbXQpCX_t.jpg" alt="Photo of a collection">
	                    <img src="http://media-cdn.pinterest.com/upload/230246599669236753_IolqlmvL_t.jpg" alt="Photo of a collection">
	                </a>
	            </div>
	            <div style="margin:5px 15px 5px 15px;">
	            	<a href="/collection_edit/{{collection.id}}/"><button class="button_edit">Edit</button></a>
	            </div>
			</div>
		{% endfor %}
	</div>
</div>
<div class="cleardiv">
</div>
{% include "footer.html" %}

pinme/templates/collection_pin_list.html
{% include "header.html" %}
<div class="wrap_board">
	{% include "profile_my.html" %}
	<div id="collection_bar">
	     <p id="bar_links">My favorite stuff</p>
		 <div style="text-align:right;">
			 <button style="width:200px;" class="button_edit">Edit collection</button></a>
		 </div>
    </div>
    <div id="collection_board">
		<div class="content_photo clearfix">
					{% for pin in pin_list %}
							<div class="post clearfix">
								<div class="like_buttons">
									<ul id="like_but">
										<li class="like_buttons_design">
											<a href="#"><img src="/static/images/like.png" alt="like" class="like_img">
												Like
											</a>
										</li>
										<li class="like_buttons_design">
											<a href="#"><img src="/static/images/comment.png" alt="comment" class="like_img">
												Comment
											</a>
										</li>
										<li class="like_buttons_design">
											<a href="#"><img src="/static/images/copy.png" alt="copy" class="like_img">
												Copy
											</a>
										</li>
									</ul>
								</div>
								<div class="clip">
									<a href="#">
										<img src="/show_image/{{pin.img.id}}"  alt="green" class="clip_img">
									</a>
									<p>{{pin.alt}}</p>
								</div>
								<div class="clip_comments">
									<a href="http://www.flickr.com">{{pin.alt}}flickr.com 
									</a>
								</div>
							</div>
					{% endfor %}
		</div>
	</div>
</div>
		<script type="text/javascript">
			$(document).ready(function(){
				$('img').load(function(){
					$(".content_photo").masonry();
				});
				$(".content_photo").masonry();
							
			});
		</script>
	</body>
{% include "footer.html" %}

pinme/templates/footer.html
		<BR />
		<h1 class="copyright">© Darko & Jest. 2011. All rights reserved.</h1>
		<BR />
		<BR />
	</BODY>
</HTML>

pinme/templates/header.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Clipepper</title>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
		<meta http-equiv="Content-Style-Type" content="text/css">	
		<link href="/static/css/pinme_style.css" rel="stylesheet" type="text/css">
		<link href="/static/images/favicon.png" rel="shortcut icon" type="image/x-icon" />
		<script type="text/javascript" src="/static/jquery/jquery.js"></script>
		<script type="text/javascript" src="/static/jquery/masonry/jquery.masonry.js"></script>
		<script type="text/javascript" src="/static/jquery/jquery.form.js"></script> 
		<script type="text/javascript" src="/static/js/tools.js"></script> 
	</head>
		<script>
			$(function(){
				$('a.pin_button').attr('href',"javascript:void((function(){var e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','http://"+window.location.host+"/js/btn.js?r='+Math.random()*99999999);document.body.appendChild(e)})());")
				$('#nav li').hover(
					        function () {
					            //show its submenu
					            $('ul', this).slideDown(100);
					 
					        }, 
					        function () {
					            //hide its submenu
					            $('ul', this).slideUp(100);         
					        }
				);				
			})
		
		</script>
	<body>
		<div id="ErrorMessage" class="error-message">
			{% if error_messages %}
				{% for error in error_messages %}
					{{ error }}
				{% endfor %}
			{% endif %}
		</div>
		<div id="message"></div>
		<div id="curtains"></div>
		<div id="header">
			<div id="label">
				<a class="pin_button" href="" title="Clipper"><img src="/static/images/pepper.png" alt="Clipepper" id="pepper_img"></a>Clipepper
			</div>
			<div id="main_menu">
				{% if request.session.user %}
					{% include "menu_main.html" %}
				{% else %}
					{% include "menu_main_unlogged.html" %}
				{% endif %}
			</div>
		</div>


	
	

pinme/templates/img_list.html
{% include "header.html" %}
		<div id="wrapper" class="wrap_board">
			<div id="column_content">
				<div class="content_photo clearfix">
					{% for pin in pin_list %}
							<div class="post clearfix">
								<div class="like_buttons">
									<ul id="like_but">
										<li class="like_buttons_design">
											<a href="#"><img src="/static/images/like.png" alt="like" class="like_img">
												Like
											</a>
										</li>
										<li class="like_buttons_design">
											<a href="#"><img src="/static/images/comment.png" alt="comment" class="like_img">
												Comment
											</a>
										</li>
										<li class="like_buttons_design">
											<a href="#"><img src="/static/images/copy.png" alt="copy" class="like_img">
												Copy
											</a>
										</li>
									</ul>
								</div>
								<div class="clip">
									<a href="#">
										<img src="/show_image/{{pin.img.id}}"  alt="green" class="clip_img">
									</a>
									{{pin.alt}}
								</div>
								<div class="clip_comments">
									<p>{{pin.alt}} Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque sit amet massa eu mauris accumsan sodales. 
										Vestibulum eleifend tincidunt ullamcorper. Nullam molestie arcu non quam viverra quis consequat ipsum hendrerit.
									</p>
								</div>
							</div>
					{% endfor %}
				</div>
			</div>	
		</div>
		
		<script type="text/javascript">
			$(document).ready(function(){
				$('img').load(function(){
					$(".content_photo").masonry();
				});
				$(".content_photo").masonry();
							
			});
		</script>
	</body>
{% include "footer.html" %}

pinme/templates/install_pinbtn.html
<html>
<body>
	Please drug and drop this button on the bookmarks panel of your browser.
<!-- 	<a id="BigPinItButton" onclick="return false;" href="javascript:void((function(){var e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','http://localhost:8000/static/js/btn.js?r='+Math.random()*99999999);document.body.appendChild(e)})());" title="Clipper"> -->
	<a id="BigPinItButton" onclick="return false;" href="javascript:void((function(){var e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','http://zxscript.com:9000/static/js/btn.js?r='+Math.random()*99999999);document.body.appendChild(e)})());" title="Clipper">
	<img src="/static/images/pinbtn2.jpg" alt="Clipper" title="Clipper">
	</a>
</body>



</html>

pinme/templates/login.html
{% include "header.html" %}
<div id="login_layout">
	<div id="login_sublayout">
		<img src="/static/images/strip.png" alt="strip">
		{% if error_message_list %}
			{% for error_message in error_message_list %}
				<div class="error_message">{{error_message}}</div>
			{% endfor %}
		{% endif %}
		<form method="post" action="" class="login_signin">
			{% csrf_token %}
			<label>Username:</label>
			<input type="text" value="" placeholder="Username" name="username"><br />
			{{ form.username.errors }}
			<label>Password:</label>
			<input type="password" role="signin_password" placeholder="Password" name="password"><br />
			{{ form.password.errors }}
			<div class="last_singin">
				<input type="submit" value="Login" name="commit" class="submit_button">
				<a id="login_remind" href="/restore_password/">Forgot your password?</a>
            </div>
		</form>
		<img src="/static/images/strip.png" alt="strip">
	</div>
</div> 
{% include "footer.html" %}


    
    
    

pinme/templates/menu_main.html
			<ul id="nav">
			    <li><a href="#">Add +</a>
			        <ul>
			            <li><a href="#" class="inactive">Add Pin</a></li>
			            <li><a href="#" class="inactive">Upload Pin</a></li>
			            <li><a href="/collection_create/">Create Collection</a></li>
			        </ul>
			        <div class="clear"></div>
			    </li>
			    <li><a href="#" class="selected">Help </a>
			        <ul>
			            <li><a href="#" class="inactive">Pin Button</a></li>
			            <li><a href="#" class="inactive">Copyright</a></li>
			            <li><a href="#" class="inactive">About Us</a></li>
			        </ul>
			        <div class="clear"></div>
			    </li>
			    <li><a href="#">Friends</a>
				    <ul>
				        <li><a href="#" class="inactive">Invite Friends</a></li>
				        <li><a href="#" class="inactive">Find Friends</a></li>
				    </ul>         
			        <div class="clear"></div>
			    </li>
			    <li><a href="#" class="username">{{request.session.user.username}}</a>
				    <ul>
				        <li><a href="/collection_list/">Collections</a></li>
				        <li><a href="/collection_pin_list/">Pins</a></li>
				        <li><a href="#" class="inactive">Likes</a></li>
				        <li><a href="/settings/">Settings</a></li>
				        <li><a href="/logout/">Log out</a></li>
				    </ul>         
			        <div class="clear"></div>
			    </li>
			</ul>
			<div class="clear"></div>

pinme/templates/menu_main_unlogged.html
			<ul id="nav">
			    <li><a href="#" class="selected">Help </a>
			        <ul>
			            <li><a href="#" class="inactive">Pin Button</a></li>
			            <li><a href="#" class="inactive">Copyright</a></li>
			            <li><a href="#" class="inactive">About Us</a></li>
			        </ul>
			        <div class="clear"></div>
			    </li>
			    <li><a href="/login/">Login</a></li>
			    <li><a href="/register/">Register</a></li>
			</ul>
			<div class="clear"></div>

pinme/templates/profile_edit.html
{% include "header.html" %}
<div id="login_layout">
	<div id="login_sublayout">
		<p>Edit Profile:</p>
		<img src="/static/images/strip.png" alt="strip">
		{% if error_message_list %}
			{% for error_message in error_message_list %}
				<div class="error_message">{{error_message}}</div>
			{% endfor %}
		{% endif %}
		<form method="post" action="" class="login_signin">
			{% csrf_token %}
			<label>Email:</label>
			{{ form.email }}
			{{ form.email.errors }}
			<br /><br />
			<label>First Name:</label>
			{{ form.first_name }}
			{{ form.first_name.errors }}
			<br /><br />
			<label>Last Name:</label>
			{{ form.last_name }}
			{{ form.last_name.errors }}
			<br /><br />
			<label>Username:</label>
			{{ form.username }}
			{{ form.username.errors }}
			<br /><br />
			<label>About:</label>
			{{ form.about }}
			{{ form.about.errors }}
			<br /><br />
			<label>Web-site:</label>
			{{ form.site }}
			{{ form.site.errors }}
			<br /><br />
			<div class="last_singin">
				<input type="submit" value="Save" name="commit" class="submit_button">
            </div>
		</form>
		<img src="/static/images/strip.png" alt="strip">
	</div>
</div> 
{% include "footer.html" %}


    
    
    

pinme/templates/profile_my.html
	<div id="profile">
		<h1>{{request.session.user.username}}</h1>
		<p>
			<a href="#">0
			<span> followers</span></a>
			<a href="#">11
			<span> following</span></a>
		</p>
		<div id="profile_img">
	       	<a href="#" class="link_img" target="_blank">
	       		<img src="/static/tmp/images/angelina-jolie.jpg" alt="Profile Picture of Angelina">
	       	</a>
			<a href="/settings/">
				<button class="button_edit">Edit Profile</button>
			</a>
    	</div>
    	<ol class="list_activity">
			<li>
			    <a href="/pin/37436240622369122/" class="link_img">
			        <img src="http://media-cdn.pinterest.com/upload/220606081716870518_GuJP7QT0_t.jpg" alt="user image">
			    </a>
			    Angelina repinned happy work space to 
			    <a href="#">Favorite Places &amp; Spaces</a>.
			    <span class="colorlight">just now</span>
			</li>
			<li>
			    <a href="/pin/37436240622369120/" class="link_img">
			        <img src="http://media-cdn.pinterest.com/upload/105060603777135638_TUGVEANf_t.jpg" alt="user image">
			    </a>
			    Angelina repinned . to 
			    <a href="/natalles/favorite-places-spaces/">Favorite Places &amp; Spaces</a>.
			    <span class="colorlight">just now</span>
			</li>
		</ol>
	</div>

pinme/templates/register.html
{% include "header.html" %}
<div id="login_layout">
	<div id="login_sublayout">
		<p>Registration</p>
		<img src="/static/images/strip.png" alt="strip">
		{% if error_message_list %}
			{% for error_message in error_message_list %}
				<div class="error_message">{{error_message}}</div>
			{% endfor %}
		{% endif %}
		<form method="post" action="" class="login_signin">
			{% csrf_token %}
			<label>Username:</label>
			<input type="text" value="" placeholder="Username" name="username"><br />
			{{ form.username.errors }}
			<label>Email:</label>
			<input type="email" value="" placeholder="Email" name="email"><br />
			{{ form.email.errors }}
			<label>Password:</label>
			<input type="password" role="signin_password" placeholder="Password" name="password"><br />
			{{ form.password.errors }}
			<label>Repeat Password:</label>
			<input type="password" role="signin_password" placeholder="Repeat Password" name="password_repeat"><br />
			{{ form.password_repeat.errors }}
			<div class="last_singin">
				<input type="submit" value="Register" name="commit" class="submit_button">
            </div>
		</form>
		<img src="/static/images/strip.png" alt="strip">
	</div>
</div> 
{% include "footer.html" %}

pinme/templates/upload_selected_images.html
{% include "header.html" %}
<script language="javascript">
	$(function(){
//		$('img.loader').show();
		$('img.loader').hide();
//		$('img.loader').show();
		
		$('button.save_btn').click(function(){
			$(this).hide().siblings('img.loader').show();
			var data_container_div=this;
			var data_container_div=this;
			$.post('/save_selected_image/',
					{
						csrfmiddlewaretoken:'{{ csrf_token }}',
						url:$('input#from_url').val(),
						src:$(this).parent().parent().find('input.src').val(),
						alt:$(this).parent().parent().find('textarea.alt').val(),
						collection:$(this).parent().parent().find('select#id_collection').val()
					},
					function(data){
						if (data=='ok'){
							console.log($('.save_btn').length);
							if ($('.save_btn').length>1){
								$(data_container_div).parent().parent().slideUp('slow',function(){
									$(this).remove();
								})
							}else{
								window.location='/collection_pin_list/';
//								$('body').load('/collections/');
							}
						}
					}
				);
			return false;
		});
	});
</script>

<div id="upload_confirmation_form">
	<form>
<!-- 	<center> From URL: {{ from_url }}</center><br /> -->
		<input id="from_url" type="hidden" value="{{ from_url }}" />
		{% for key, an_img in img_dict.items %}
				<div class="data_container">
	<!-- 				SRC: {{ an_img.src }}<br /> -->
					<div class="upload_img">
							<input class="src" type="hidden" value="{{ an_img.src }}" />
						<img class="upload_thumbnail" src="{{ an_img.src }}"> <br />
					</div>
					<div class="uload_alt_description">
						<label>Collection:</label>
						{{form.collection}}
						<textarea class='alt' rows="7" cols="62">{{ an_img.alt }}</textarea> <br /><br />
						<button class="save_btn">Save Image</button>
						<img class="loader" src="/static/images/loader2.gif" alt="Saving..." /> 
					</div>
 					<div class="cleardiv"></div>
				</div>
			<div class="cleardiv"></div>
		{% endfor %}
			</form>
		<br />
		<br />
		<br />
</div>
<!-- 	POST:{{ output }}<br /> -->
{% include "footer.html" %}